databaseChangeLog:
- changeSet:
    id: 1774138719006-1
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: passportPK
            name: id
            type: BIGINT
        - column:
            name: created_date
            type: TIMESTAMP(6) WITH TIME ZONE
        - column:
            name: description
            type: VARCHAR(255)
        - column:
            name: name
            type: VARCHAR(255)
        tableName: passport
- changeSet:
    id: 1774138719006-2
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: passport_itemsPK
            name: passport_id
            type: BIGINT
        - column:
            name: items
            type: BIGINT
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: passport_itemsPK
            name: items_order
            type: INTEGER
        tableName: passport_items
- changeSet:
    id: 1774138719006-3
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: profilePK
            name: id
            type: BIGINT
        - column:
            name: alias
            type: VARCHAR(255)
        - column:
            name: created_date
            type: TIMESTAMP(6) WITH TIME ZONE
        - column:
            name: first_name
            type: VARCHAR(255)
        - column:
            name: is_active
            type: BOOLEAN
        - column:
            name: last_name
            type: VARCHAR(255)
        - column:
            name: location
            type: VARCHAR(255)
        - column:
            name: nick_name
            type: VARCHAR(255)
        - column:
            name: period
            type: VARCHAR(255)
        - column:
            name: profile_email
            type: VARCHAR(255)
        - column:
            name: type
            type: VARCHAR(255)
        - column:
            name: user_id
            type: BIGINT
        tableName: profile
- changeSet:
    id: 1774138719006-4
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: profile_passportPK
            name: profile_id
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: passports_id
            type: BIGINT
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: profile_passportPK
            name: passports_order
            type: INTEGER
        tableName: profile_passport
- changeSet:
    id: 1774138719006-5
    author: anton (generated)
    changes:
    - addUniqueConstraint:
        columnNames: passports_id
        constraintName: UC_PROFILE_PASSPORTPASSPORTS_ID_COL
        tableName: profile_passport
- changeSet:
    id: 1774138719006-6
    author: anton (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: profile_id
        baseTableName: profile_passport
        constraintName: FKfxew29j0hsrcmyfqryirq7mug
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: profile
        validate: true
- changeSet:
    id: 1774138719006-7
    author: anton (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: passports_id
        baseTableName: profile_passport
        constraintName: FKhfujj22nsa8g5poku4m9f2ojd
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: passport
        validate: true
- changeSet:
    id: 1774138719006-8
    author: anton (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: passport_id
        baseTableName: passport_items
        constraintName: FKsre85gece1ayjqlgil8upktm3
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: passport
        validate: true

